import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';

const PDFExportService = {
    async generateAndSharePDF(userData, dailyLogs, dateRangeLabel) {
        try {
            const html = this.createHTML(userData, dailyLogs, dateRangeLabel);
            const { uri } = await Print.printToFileAsync({ html });
            await Sharing.shareAsync(uri, { UTI: '.pdf', mimeType: 'application/pdf' });
        } catch (error) {
            console.error('Error generating PDF:', error);
            throw error;
        }
    },

    createHTML(user, logs, rangeLabel) {
        const rows = logs.map(log => `
            <tr>
                <td>${log.date}</td>
                <td>${log.steps || 0}</td>
                <td>${log.caloriesConsumed || 0}</td>
                <td>${log.caloriesBurned || 0}</td>
                <td>${log.macrosConsumed?.protein || 0}g</td>
                <td>${log.macrosConsumed?.carbs || 0}g</td>
                <td>${log.macrosConsumed?.fat || 0}g</td>
            </tr>
        `).join('');

        return `
            <!DOCTYPE html>
            <html>
                <head>
                    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no" />
                    <style>
                        body { font-family: 'Helvetica', sans-serif; padding: 20px; color: #333; }
                        h1 { color: #4CAF50; text-align: center; }
                        .header { margin-bottom: 30px; border-bottom: 2px solid #4CAF50; padding-bottom: 10px; }
                        .user-info { margin-bottom: 20px; font-size: 14px; }
                        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
                        th, td { border: 1px solid #ddd; padding: 12px; text-align: left; font-size: 12px; }
                        th { background-color: #f2f2f2; color: #333; }
                        tr:nth-child(even) { background-color: #f9f9f9; }
                        .footer { margin-top: 30px; text-align: center; font-size: 10px; color: #aaa; }
                    </style>
                </head>
                <body>
                    <div class="header">
                        <h1>Nutrition & Fitness Report</h1>
                        <p style="text-align:center;">${rangeLabel}</p>
                    </div>
                    
                    <div class="user-info">
                        <p><strong>Name:</strong> ${user.name}</p>
                        <p><strong>Goal:</strong> ${user.profile?.goal || 'N/A'}</p>
                    </div>

                    <table>
                        <thead>
                            <tr>
                                <th>Date</th>
                                <th>Steps</th>
                                <th>Cals In</th>
                                <th>Cals Out</th>
                                <th>Protein</th>
                                <th>Carbs</th>
                                <th>Fat</th>
                            </tr>
                        </thead>
                        <tbody>
                            ${rows}
                        </tbody>
                    </table>

                    <div class="footer">
                        Generated by LPU Food Scanner
                    </div>
                </body>
            </html>
        `;
    }
};

export default PDFExportService;
